version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
branches:
  only:
  - master
  - appveyor_test
environment:
  WHEEL_DIR: C:\kivy_wheels
  COMPILER: mingw
  KIVY_BUILD_DIR: C:\kivy_build
  KIVY_BUILD_CACHE: C:\kivy_build_cache2
  AIRPLANE_CHARGE:
    secure: HgQr7XMKpB6lWn33SKv0GyYZbh1RfpgvaIKEE0B54R5XHJujQg5dhOEB3Vc2CfAqCprX+CGxXAjQwFnuv6pJeA3++9Z8/1SfFuEqCF59J7PqsDs2thA8lNHLRsThvRVJrBt2jcb1wrG3Nf3sz3vi7e+rBzYjprkcYiTP0XJ5FdQekyFTTjuXYaRBGWrwGX81dEVVUkGFuEZFYWJq2Yf/PkFGOX+IN0CjgpFB0pGfZSJcIG7mvscurfG/KvckLhNUINprUKt0pJ8iCN0iufsbmrOnuG+WC8AHktvlSxzHSfCm8zmhSZTkDNkJfpYHapFagQQThmiYq8PqsVIC0XOz+j4KLljc6bxyhE0oPtOPg4DohBdqLI28V1XB/Kqh7CCZR50wAw567voWVOtKsyets5oeywZH1q/gtK6stC5t7v+a2s0w1I2IEW6p2aPy7plreZj15QCgIR8h6JgIuMuwqiaVCUuhej/GauCZG/9jIBJpTf1NkBa9k4vIxHPq5R5/ltYX8za49vz5ImdLe1qlTFwy9fegMpb+D5m3y3ilm+t5xkDmqXQau1oVWIVd8jf0DawWqkNsKLp6hbYr51gclS+Gc7NVKwvFtcmoAfbvNCGBDH4vF6cR2wNhy6RDjjqDgIStnpUs3fKS9bKOyrv9+394esQqEuAXgLtC2vUMk+z3Hf8V18AFYKZfZmWxiGGrjI6YQCBOBOdh5VO5cASqtoTU22OvAPhXT7gX2JG96Rc9yf/K8DEvzuWo3lArDAclh2zLm++1SOh54dDiAiMZvLkNXu5tAsg60c+rJCx4FQ9ra0/GcFY1LKJntdKvpQyBkp4wKAvq3YyV7Rnx8u6PULXXG2rS6i7m+asLrY+FSCO5oRmLrMv5pEv0cF/BOAh0RGR6medX8ASmM40sHqz+WC9WJfaSUZplSzQwHxXCr/AzK40mOTtKgkg8e8tqwNzjI8mdjx0kwcu8zuOeUK6U6l83voGKbli1gzinkLvzhjvF1TXZwpT1y/HvAs5dGwXVfdigeOqcfmIOxXStPmaZ4CZRKVK3CgweYzpETyT6Pm5H3jANcAuyYuphJr7YrfHfWKAg6N3Q0r3AfzliOuIBm3DVfm2RuI8USGJxRsjaDX8LB8sdhrCPLUYBh1RNhYol5bVEM1IX+BcpXzIyqv00eSMTvN3G7KdsM+/8LGlnEM+apIgnBlVfcWOQI8rzBkXuJvExSwDhKzncGWbi12UapEVsE/QnVpDiwbiPdZtQQzQ=
  GDRIVE_CLIENT_ID:
    secure: iGAZpJPOTLhRmK7X60xzRZm1S0PbmoMwoVJdd8WiKBH34Tqsd6UEFhPjLLok7J0+xWStS8E3fwEQh4Wzn1BCXhry5Qv8FLD41oskVpiSwdc=
  GDRIVE_CLIENT_SECRET:
    secure: 7J8TZnhr3MsF5rveMVVkbrr9tzTwGG6rHWZMorW0WN4=
  GDRIVE_sdl2_UPLOAD_ID: 0B1_HB9J8mZepTVJhenRET01VQTQ
  GDRIVE_sdl2_dev_UPLOAD_ID: 0B1_HB9J8mZepWlZMNWVKVHE5R28
  GDRIVE_glew_UPLOAD_ID: 0B1_HB9J8mZepUkJ3TTJhY0ZuWGs
  GDRIVE_glew_dev_UPLOAD_ID: 0B1_HB9J8mZepak1KeGJ5MDdSQ0E
  GDRIVE_gstreamer_UPLOAD_ID: 0B1_HB9J8mZepNzZ5aW91Q0tJU2s
  GDRIVE_gstreamer_dev_UPLOAD_ID: 0B1_HB9J8mZepZzNSZVI2V19mQ00
  GDRIVE_angle_UPLOAD_ID: 0B1_HB9J8mZepRDltSDB6Z0FVT00
  GDRIVE_angle_dev_UPLOAD_ID: fake
  matrix:
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: sdl2
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: sdl2
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 36
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: sdl2
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: sdl2
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 36
    BITTNESS: 64
    COMPILER: msvc
cache: C:\kivy_build_cache2
build_script:
- ps: >-
    function Check-Error
    {
      param([int]$SuccessVal = 0)
      if ($SuccessVal -ne $LastExitCode) {
        throw "Failed with exit code $LastExitCode"
      }
    }


    $env:SSL_CERT_FILE="C:\projects\kivy-sdk-packager\win\DST Root CA X3.pem"

    cd C:\projects\kivy-sdk-packager


    mkdir "$env:KIVY_BUILD_DIR"

    mkdir "$env:WHEEL_DIR"

    if (!(Test-Path "$env:KIVY_BUILD_CACHE")) {
      mkdir "$env:KIVY_BUILD_CACHE"
    }

    $GDRIVE_ID = [Environment]::GetEnvironmentVariable("GDRIVE_$env:PACKAGE_TARGET`_UPLOAD_ID", "Process")

    $DEV_GDRIVE_ID = [Environment]::GetEnvironmentVariable("GDRIVE_$env:PACKAGE_TARGET`_dev_UPLOAD_ID", "Process")



    if ($env:BITTNESS -eq "64") {
      $PYTHON_ROOT = "C:\Python$env:PYVER-x64"
      $WHELL_BITNESS = "win_amd64"
    } else {
      $PYTHON_ROOT = "C:\Python$env:PYVER"
      $WHELL_BITNESS = "win32"
    }

    $env:PATH = "$PYTHON_ROOT;$PYTHON_ROOT\Scripts;$env:PATH"



    $WHEEL_VERSION = python -c "import win.$env:PACKAGE_TARGET;print(win.$env:PACKAGE_TARGET.__version__)"

    Check-Error

    $WHEEL_BIN = "kivy.deps.$env:PACKAGE_TARGET-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"

    $WHEEL_DEV = "kivy.deps.$env:PACKAGE_TARGET`_dev-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"


    C:\Python27\Scripts\pip.exe install pydrive

    Check-Error

    $ALREADY_EXISTS = C:\Python27\python.exe win\gdrive.py exists "$GDRIVE_ID" "$WHEEL_BIN"

    Check-Error

    if ($ALREADY_EXISTS -eq "True" -and $DEV_GDRIVE_ID -ne "fake") {
      $ALREADY_EXISTS = C:\Python27\python.exe win\gdrive.py exists "$DEV_GDRIVE_ID" "$WHEEL_DEV"
      Check-Error
    }

    echo "Already exists=$ALREADY_EXISTS $WHEEL_BIN $WHEEL_DEV"


    if ($ALREADY_EXISTS -eq "False") {
      python -m pip install pip wheel setuptools --upgrade
      Check-Error
      if ($env:COMPILER -eq "mingw") {
        pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
        Check-Error
      }

      echo "Executing win.$env:PACKAGE_TARGET build_path $env:KIVY_BUILD_DIR arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output $env:WHEEL_DIR cache $env:KIVY_BUILD_CACHE compiler $env:COMPILER"
      python -m win.$env:PACKAGE_TARGET build_path "$env:KIVY_BUILD_DIR" arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output "$env:WHEEL_DIR" cache "$env:KIVY_BUILD_CACHE" compiler "$env:COMPILER"
      Check-Error

      if ($DEV_GDRIVE_ID -ne "fake") {
        C:\Python27\python.exe win\gdrive.py upload "$DEV_GDRIVE_ID" "$env:WHEEL_DIR\kivy.deps.$env:PACKAGE_TARGET`_dev*"
        Check-Error
      }
      C:\Python27\python.exe win\gdrive.py upload "$GDRIVE_ID" "$env:WHEEL_DIR\kivy.deps.$env:PACKAGE_TARGET-*"
      Check-Error
    }
